services:
  - type: web
    name: whatsapp-chat-bot
    runtime: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -Dserver.port=8080 -jar target/whatsapp-chatbot-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.java
    plan: free
